### PR TITLE
✨ single-file output

### PR DESCRIPTION
**Pull request by Seele0oO**
https://learn.microsoft.com/zh-cn/dotnet/core/deploying/single-file/overview?tabs=cli

### CODE REVIEW

**Comment by qyl27** [comment]
How about use command line argument instead of modifing csproj file?

**Comment by Seele0oO** [comment]
command line argument is `-p:PublishSingleFile=true`
Error
```log
/usr/share/dotnet/sdk/8.0.106/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(183,5): error NETSDK1099: Publishing to a single-file is only supported for executable applications. [/home/seele/Projects/CatMessenger-Adapter/CatMessenger.Core/CatMessenger.Core.csproj]
```

**Comment by qyl27** [comment]
> command line argument is `-p:PublishSingleFile=true` Error
> 
> ```
> /usr/share/dotnet/sdk/8.0.106/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(183,5): error NETSDK1099: Publishing to a single-file is only supported for executable applications. [/home/seele/Projects/CatMessenger-Adapter/CatMessenger.Core/CatMessenger.Core.csproj]
> ```

Can not reproduce, please build CatMessenger.Telegram project instead of Core project.

**Comment by Seele0oO** [comment]
ok,done.

**Pull request closed without merging**
